#!/usr/bin/env python3
"""Transcribe the in-game help database MBMGEHLP.MSG to markdown.

Entry format (one text option per help screen):

    HLPIMP {***
    The Impulse command directs your impulse (sub-light) engines ...
    } T

The leading *** and the ANSI escape sequences (colors, clear-screen)
are display dressing and are stripped; the text itself is emitted
verbatim inside fenced blocks, one section per entry, in file order.
"""
import re

SRC = "/Users/jim/develop/ge/mbmgemp/MBMGEHLP.MSG"
OUT = "/Users/jim/develop/ge/docs/original/online-help.md"

ANSI = re.compile(r"\x1b\[[0-9;]*[A-Za-z]")

# What the player types to reach each entry (help dispatch in GECMDS.C).
TITLES = {
    "HLPINDEX": "help (index)",
    "HLPSTART": "help starting",
    "HLPGALXY": "help galaxy",
    "HLPSECTR": "help sector",
    "HLPCOMMU": "help communicate",
    "HLPNAVIG": "help moving",
    "HLPPLANT": "help planets",
    "HLPPLAN2": "help planets (screen 2)",
    "HLPPLAN3": "help planets (screen 3)",
    "HLPSTRAT": "help strategy",
    "HLPBATTL": "help battle",
    "HLPBATT2": "help battle (screen 2)",
    "HLPBATT3": "help battle (screen 3)",
    "HLPCYBER": "help cybertron",
    "HLPSCORE": "help scoring",
    "HLPWORM": "help wormholes",
    "HLPHYP": "help hyper (hyper-phasers)",
    "HLPCLS1": "help class (table header)",
    "HLPCLS2": "help class (table footer/legend)",
    "HLPCLS3": "help class nn (bad class number)",
    "HLPABA": "help abandon",
    "HLPABO": "help abort",
    "HLPADM": "help admin",
    "HLPATT": "help attack",
    "HLPBUY": "help buy",
    "HLPCLO": "help cloak",
    "HLPCLS": "help cls",
    "HLPDEC": "help decoy",
    "HLPDES": "help destruct",
    "HLPFLU": "help flux",
    "HLPFRE": "help freq",
    "HLPHEL": "help help",
    "HLPIMP": "help impulse",
    "HLPJAM": "help jammer",
    "HLPJET": "help jettison",
    "HLPLOC": "help lock",
    "HLPMAI": "help maintenance",
    "HLPMIN": "help mine",
    "HLPMIS": "help missile",
    "HLPNAV": "help navigate",
    "HLPNEW": "help new",
    "HLPNEW2": "help newprice",
    "HLPORB": "help orbit",
    "HLPPHA": "help phaser",
    "HLPPLA": "help planet",
    "HLPPRI": "help price",
    "HLPREN": "help rename",
    "HLPREP": "help report",
    "HLPROS": "help roster",
    "HLPROT": "help rotate",
    "HLPSCA": "help scan",
    "HLPSEL": "help sell",
    "HLPSEN": "help send",
    "HLPSET": "help set",
    "HLPSHI": "help shield",
    "HLPSPY": "help spy",
    "HLPTEA": "help team",
    "HLPTOR": "help torpedo",
    "HLPTRA": "help transfer",
    "HLPWAR": "help warp",
    "HLPZIP": "help zipper",
}

entries = []          # (name, [lines])
name, lines, version = None, [], "?"
for raw in open(SRC, encoding="latin-1"):
    line = ANSI.sub("", raw.rstrip("\n"))
    if name is None:
        if line.startswith("Version "):
            version = line[len("Version "):].strip()
        m = re.match(r"^([A-Z][A-Z0-9]*) \{(.*)$", line)
        if not m:
            continue
        name, first = m.group(1), m.group(2)
        if first.rstrip() in ("}", "} T"):        # empty entry (LEVEL5)
            name = None
            continue
        lines = [] if first.strip() in ("", "***") else [first]
    elif re.match(r"^\} ?T?\s*$", line):
        while lines and not lines[-1].strip():
            lines.pop()
        entries.append((name, lines))
        name, lines = None, []
    else:
        lines.append(line)

with open(OUT, "w") as f:
    f.write(f"""# Galactic Empire — Online Help (transcription)

Faithful transcription of the in-game help database
`mbmgemp/MBMGEHLP.MSG` ("Galactic Empire Help Message Database,
Version {version}"), the newest of the three copies in the repository
(it alone documents the `set filter` option). Each section below is
one help screen, shown exactly as the game printed it (ANSI color and
clear-screen codes stripped, original wording, spelling and spacing
preserved). Headings give the command a player typed to see it.

Generated by `salvage/tools/extract_help.py` — do not edit by hand.

The `HLPCLS1`/`HLPCLS2` screens are only the header and legend of the
ship-class table: the game filled in the rows at runtime from the ship
database (see `salvage/data/ships.toml` for the shipped values).
""")
    for name, lines in entries:
        title = TITLES.get(name, name)
        f.write(f"\n## `{title}` — {name}\n\n```text\n")
        f.write("\n".join(lines))
        f.write("\n```\n")

print(f"wrote {OUT}: {len(entries)} entries")
